import { formatDate, parseDateValue, parseTimestampValue } from "@/lib/date/dates";
import { FLAG_META, LIMIT_STATUS_META, REHIRE_STATUS_META, STATUS_META } from "@/lib/domain/meta";
import {
  COMPANIES,
  CONTRACT_TYPES,
  RENEWAL_STATUSES,
  WORKER_TYPES,
  type Company,
  type Contract,
  type ContractType,
  type EvaluatedContract,
  type RenewalStatus,
  type WorkerType,
} from "@/lib/domain/types";

/**
 * The Google Sheet layout.
 *
 * Columns are matched by header text, not by position, so HR can reorder or
 * insert columns in the sheet without breaking the system. `input` columns are
 * captured by people; `calculated` columns are written back by the system on
 * every system check.
 */
export type InputColumnKey =
  | "id"
  | "employeeId"
  | "employeeName"
  | "employeeEmail"
  | "company"
  | "workerType"
  | "department"
  | "costCentre"
  | "jobTitle"
  | "contractType"
  | "startDate"
  | "endDate"
  | "contractNumber"
  | "renewalStatus"
  | "hrPerson"
  | "hrEmail"
  | "manager"
  | "managerEmail"
  | "location"
  | "notes"
  | "lastUpdated";

export type CalculatedColumnKey =
  | "contractCount"
  | "daysRemaining"
  | "status"
  | "limitStatus"
  | "rehireEligibleDate"
  | "rehireStatus"
  | "flags";

export type ColumnKey = InputColumnKey | CalculatedColumnKey;

export interface SheetColumn {
  key: ColumnKey;
  header: string;
  /** Other header spellings accepted when reading an existing sheet. */
  aliases?: string[];
  kind: "input" | "calculated";
  type: "text" | "date" | "number" | "datetime";
  /** Dropdown values applied by the sheet setup script. */
  options?: readonly string[];
  width?: number;
  note?: string;
}

export const CONTRACT_COLUMNS: SheetColumn[] = [
  { key: "id", header: "Contract ID", kind: "input", type: "text", width: 130, note: "Generated by the system when left blank." },
  { key: "employeeId", header: "Employee ID", kind: "input", type: "text", width: 110 },
  { key: "employeeName", header: "Employee Name", kind: "input", type: "text", width: 180 },
  { key: "employeeEmail", header: "Employee Email", kind: "input", type: "text", width: 180 },
  { key: "company", header: "Company", kind: "input", type: "text", options: COMPANIES, width: 120 },
  {
    key: "workerType",
    header: "Worker Type",
    aliases: ["Employee Category", "Employment Type", "Worker Type / Employee Category"],
    kind: "input",
    type: "text",
    options: WORKER_TYPES,
    width: 120,
  },
  { key: "department", header: "Department", kind: "input", type: "text", width: 150 },
  { key: "costCentre", header: "Cost Centre", aliases: ["Cost Center"], kind: "input", type: "text", width: 120 },
  { key: "jobTitle", header: "Job Title", aliases: ["Position", "Job Title / Position"], kind: "input", type: "text", width: 160 },
  { key: "contractType", header: "Contract Type", kind: "input", type: "text", options: CONTRACT_TYPES, width: 120 },
  { key: "startDate", header: "Contract Start Date", aliases: ["Start Date"], kind: "input", type: "date", width: 130 },
  { key: "endDate", header: "Contract End Date", aliases: ["End Date"], kind: "input", type: "date", width: 130 },
  { key: "contractNumber", header: "Contract Number", kind: "input", type: "number", width: 120, note: "Sequence for this employee. Leave blank and the system counts the rows." },
  { key: "renewalStatus", header: "Renewal Status", kind: "input", type: "text", options: RENEWAL_STATUSES, width: 130 },
  { key: "hrPerson", header: "Responsible HR Person", kind: "input", type: "text", width: 170 },
  { key: "hrEmail", header: "Responsible HR Email", kind: "input", type: "text", width: 200 },
  { key: "manager", header: "Direct Manager", aliases: ["Manager"], kind: "input", type: "text", width: 170 },
  { key: "managerEmail", header: "Manager Email", kind: "input", type: "text", width: 200, note: "Drives which manager receives this employee in the weekly report." },
  { key: "location", header: "Location / Site", aliases: ["Location", "Site"], kind: "input", type: "text", width: 130 },
  { key: "notes", header: "Notes / Comments", aliases: ["Notes", "Comments"], kind: "input", type: "text", width: 220 },
  { key: "lastUpdated", header: "Last Updated", kind: "input", type: "datetime", width: 150 },

  { key: "contractCount", header: "Contract Count", kind: "calculated", type: "number", width: 120 },
  { key: "daysRemaining", header: "Days Remaining", kind: "calculated", type: "number", width: 120 },
  { key: "status", header: "Contract Status", kind: "calculated", type: "text", width: 150 },
  { key: "limitStatus", header: "Contract Limit Status", kind: "calculated", type: "text", width: 150 },
  { key: "rehireEligibleDate", header: "Rehire Eligibility Date", kind: "calculated", type: "date", width: 150 },
  { key: "rehireStatus", header: "Rehire Status", kind: "calculated", type: "text", width: 140 },
  { key: "flags", header: "Flags", kind: "calculated", type: "text", width: 260 },
];

export const INPUT_COLUMNS = CONTRACT_COLUMNS.filter((column) => column.kind === "input");
export const CALCULATED_COLUMNS = CONTRACT_COLUMNS.filter((column) => column.kind === "calculated");

export const RUN_LOG_HEADERS = [
  "Run At",
  "Type",
  "Trigger",
  "Mode",
  "Recipients",
  "Emails Sent",
  "Rows Checked",
  "Needs Action",
  "Errors",
  "Note",
] as const;

function normaliseHeader(header: string): string {
  return header.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** Maps each known column to the zero-based index it occupies in the sheet. */
export function buildColumnIndex(headerRow: unknown[]): Map<ColumnKey, number> {
  const byNormalised = new Map<string, number>();
  headerRow.forEach((header, index) => {
    const key = normaliseHeader(String(header ?? ""));
    if (key && !byNormalised.has(key)) byNormalised.set(key, index);
  });

  const index = new Map<ColumnKey, number>();
  for (const column of CONTRACT_COLUMNS) {
    const candidates = [column.header, ...(column.aliases ?? [])];
    for (const candidate of candidates) {
      const position = byNormalised.get(normaliseHeader(candidate));
      if (position !== undefined) {
        index.set(column.key, position);
        break;
      }
    }
  }
  return index;
}

/** Headers from the schema that are missing from the sheet. */
export function missingColumns(headerRow: unknown[]): SheetColumn[] {
  const index = buildColumnIndex(headerRow);
  return CONTRACT_COLUMNS.filter((column) => !index.has(column.key));
}

function cell(row: unknown[], index: Map<ColumnKey, number>, key: ColumnKey): unknown {
  const position = index.get(key);
  return position === undefined ? undefined : row[position];
}

function text(value: unknown): string {
  return value === null || value === undefined ? "" : String(value).trim();
}

function pickOption<T extends string>(value: unknown, options: readonly T[], fallback: T): T {
  const raw = normaliseHeader(text(value));
  if (!raw) return fallback;
  const exact = options.find((option) => normaliseHeader(option) === raw);
  if (exact) return exact;
  const partial = options.find(
    (option) => raw.includes(normaliseHeader(option)) || normaliseHeader(option).includes(raw),
  );
  return partial ?? fallback;
}

export function parseCompany(value: unknown): Company {
  const raw = normaliseHeader(text(value));
  if (raw.startsWith("zim") || raw === "zk") return "Zimkings";
  if (raw.startsWith("trade") || raw === "tk") return "Trade Kings";
  return pickOption(value, COMPANIES, "Trade Kings");
}

export function parseWorkerType(value: unknown): WorkerType {
  const raw = normaliseHeader(text(value));
  if (raw.includes("casual")) return "Casual";
  if (raw.includes("blue")) return "Blue Collar";
  return pickOption(value, WORKER_TYPES, "Blue Collar");
}

export function parseContractType(value: unknown): ContractType {
  return pickOption(value, CONTRACT_TYPES, "New");
}

export function parseRenewalStatus(value: unknown): RenewalStatus {
  return pickOption(value, RENEWAL_STATUSES, "Pending");
}

/** Turns one sheet row into a contract. */
export function parseContractRow(
  row: unknown[],
  index: Map<ColumnKey, number>,
  rowNumber: number,
): Contract {
  const number = Number(text(cell(row, index, "contractNumber")));

  return {
    id: text(cell(row, index, "id")) || `ROW-${rowNumber}`,
    rowNumber,
    employeeId: text(cell(row, index, "employeeId")),
    employeeName: text(cell(row, index, "employeeName")),
    employeeEmail: text(cell(row, index, "employeeEmail")),
    company: parseCompany(cell(row, index, "company")),
    workerType: parseWorkerType(cell(row, index, "workerType")),
    department: text(cell(row, index, "department")),
    costCentre: text(cell(row, index, "costCentre")),
    jobTitle: text(cell(row, index, "jobTitle")),
    contractType: parseContractType(cell(row, index, "contractType")),
    startDate: parseDateValue(cell(row, index, "startDate")),
    endDate: parseDateValue(cell(row, index, "endDate")),
    contractNumber: Number.isFinite(number) && number > 0 ? number : null,
    renewalStatus: parseRenewalStatus(cell(row, index, "renewalStatus")),
    hrPerson: text(cell(row, index, "hrPerson")),
    hrEmail: text(cell(row, index, "hrEmail")),
    manager: text(cell(row, index, "manager")),
    managerEmail: text(cell(row, index, "managerEmail")),
    location: text(cell(row, index, "location")),
    notes: text(cell(row, index, "notes")),
    lastUpdated: parseTimestampValue(cell(row, index, "lastUpdated")),
  };
}

/** True when a sheet row holds nothing we care about. */
export function isBlankRow(row: unknown[]): boolean {
  return !row.some((value) => text(value) !== "");
}

/** The value written to each input column for a contract. */
export function inputCellValue(contract: Contract, key: InputColumnKey): string | number {
  const value = contract[key as keyof Contract];
  if (value === null || value === undefined) return "";
  return typeof value === "number" ? value : String(value);
}

/** The values written back to the calculated columns after a system check. */
export function calculatedCellValues(
  contract: EvaluatedContract,
): Record<CalculatedColumnKey, string | number> {
  const { computed } = contract;
  return {
    contractCount: computed.contractCount,
    daysRemaining: computed.daysRemaining ?? "",
    status: STATUS_META[computed.status].label,
    limitStatus: LIMIT_STATUS_META[computed.limitStatus].label,
    rehireEligibleDate: computed.rehireEligibleDate ?? "",
    rehireStatus: REHIRE_STATUS_META[computed.rehireStatus].label,
    flags: computed.flags.map((flag) => FLAG_META[flag.code].label).join(" • "),
  };
}

/** Column letter for a zero-based index (0 -> A, 26 -> AA). */
export function columnLetter(index: number): string {
  let result = "";
  let current = index;
  while (current >= 0) {
    result = String.fromCharCode((current % 26) + 65) + result;
    current = Math.floor(current / 26) - 1;
  }
  return result;
}

export function describeContractForSheet(contract: EvaluatedContract): string {
  return `${contract.employeeName} (${contract.employeeId}) — ${formatDate(contract.endDate)}`;
}

/** Headings for the settings tab an administrator edits. */
export const SETTINGS_HEADERS = ["Setting", "Value", "Notes"] as const;

export interface SettingRow {
  key: string;
  label: string;
  note: string;
  example: string;
}

/**
 * Report settings the system administrator can change without a redeploy.
 * Anything left blank falls back to the environment variables.
 */
export const SETTINGS_ROWS: SettingRow[] = [
  {
    key: "hrRecipient",
    label: "HR Report Email",
    note: "The one address that receives the complete database report.",
    example: "hr@example.com",
  },
  {
    key: "reportCc",
    label: "Report CC",
    note: "Extra addresses copied on the HR report, separated by commas.",
    example: "",
  },
  {
    key: "managerReportsEnabled",
    label: "Send Manager Reports",
    note: "Yes or No. Managers are taken from the Manager Email column.",
    example: "Yes",
  },
  {
    key: "skipEmptyManagerReports",
    label: "Skip Managers With Nothing Outstanding",
    note: "Yes or No. No means every manager is emailed every week.",
    example: "Yes",
  },
  {
    key: "firstAlertDays",
    label: "First Alert (Days Before Expiry)",
    note: "When a contract first appears as expiring.",
    example: "30",
  },
  {
    key: "secondAlertDays",
    label: "Second Alert (Days Before Expiry)",
    note: "The more urgent warning closer to the end date.",
    example: "15",
  },
  {
    key: "overdueAfterDays",
    label: "Overdue After (Days Past End Date)",
    note: "How long an expired contract may sit before it is called overdue.",
    example: "7",
  },
  {
    key: "tkTermMonths",
    label: "Trade Kings Contract Length (Months)",
    note: "The standard blue-collar contract length offered when capturing one.",
    example: "6",
  },
  {
    key: "zkMaxTermMonths",
    label: "Zimkings Maximum Contract Length (Months)",
    note: "Fixed-term contracts longer than this are flagged.",
    example: "12",
  },
  {
    key: "zkMaxContracts",
    label: "Zimkings Maximum Contracts Per Employee",
    note: "The contract limit for Zimkings blue-collar employees.",
    example: "5",
  },
  {
    key: "casualTermDays",
    label: "Casual Contract Length (Days)",
    note: "How long one casual contract runs.",
    example: "7",
  },
  {
    key: "casualMaxContracts",
    label: "Casual Maximum Contracts",
    note: "How many casual contracts an employee may have before the break.",
    example: "6",
  },
  {
    key: "casualWindowWeeks",
    label: "Casual Contract Window (Weeks)",
    note: "The period the casual contract limit is measured over.",
    example: "6",
  },
  {
    key: "casualWaitMonths",
    label: "Casual Break Before Rehire (Months)",
    note: "How long a casual employee stays out of the system after the limit.",
    example: "3",
  },
];

/** Settings that change the contract rules rather than the reports. */
export const RULE_SETTING_KEYS = [
  "firstAlertDays",
  "secondAlertDays",
  "overdueAfterDays",
  "tkTermMonths",
  "zkMaxTermMonths",
  "zkMaxContracts",
  "casualTermDays",
  "casualMaxContracts",
  "casualWindowWeeks",
  "casualWaitMonths",
];

/** Matches a settings label from the sheet back to its key. */
export function settingKeyFor(label: string): string | null {
  const normalised = normaliseHeader(label);
  return SETTINGS_ROWS.find((row) => normaliseHeader(row.label) === normalised)?.key ?? null;
}

/** Reads "Yes"/"No" style values written by people. */
export function parseSheetBoolean(value: string, fallback: boolean): boolean {
  const text = value.trim().toLowerCase();
  if (!text) return fallback;
  if (["yes", "y", "true", "1", "on"].includes(text)) return true;
  if (["no", "n", "false", "0", "off"].includes(text)) return false;
  return fallback;
}
